### ISSUE TITLE
Repository of PlayStation intro/cracktros

### ISSUE THREAD

**Issue by ijacquez** [dkoluris/pseudo#1]
Do you have a repository of these executables to try?

**Comment by koluris** [comment]
Hey Israel,
let me find them on some old backup I had and send them to you.
________________________________
Από: Israel Jacquez <notifications@github.com>
Στάλθηκε: Τετάρτη, 24 Ιουλίου 2019 4:37 πμ
Προς: dkoluris/pseudo <pseudo@noreply.github.com>
Κοιν.: Subscribed <subscribed@noreply.github.com>
Θέμα: [dkoluris/pseudo] Repository of PlayStation intro/cracktros (#1)


Do you have a repository of these executables to try?

**Comment by koluris** [comment]
OK, I've actually remembered an awesome site that hosts more than what I have. Here you go: http://www.pouet.net/prodlist.php?type%5B%5D=cracktro&platform%5B%5D=Playstation&page=1
